import type { Stock, NewsArticle, Story } from '../types';

export const MOCK_STOCKS: Stock[] = [
  {
    id: '1',
    symbol: 'NVDA',
    company: 'NVIDIA',
    price: 128.50,
    change: 3.2,
    percentChange: 2.56,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
  {
    id: '2',
    symbol: 'TSLA',
    company: 'Tesla',
    price: 245.30,
    change: -5.1,
    percentChange: -2.04,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
  {
    id: '3',
    symbol: 'JPM',
    company: 'JPMorgan Chase',
    price: 198.75,
    change: 2.8,
    percentChange: 1.43,
    sector: 'Finance',
    sectorColor: '#3b82f6',
  },
  {
    id: '4',
    symbol: 'JNJ',
    company: 'Johnson & Johnson',
    price: 162.45,
    change: 1.2,
    percentChange: 0.74,
    sector: 'Healthcare',
    sectorColor: '#ec4899',
  },
  {
    id: '5',
    symbol: 'XOM',
    company: 'ExxonMobil',
    price: 115.20,
    change: -2.3,
    percentChange: -1.96,
    sector: 'Energy',
    sectorColor: '#f59e0b',
  },
  {
    id: '6',
    symbol: 'MSFT',
    company: 'Microsoft',
    price: 420.65,
    change: 4.5,
    percentChange: 1.08,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
  {
    id: '7',
    symbol: 'AAPL',
    company: 'Apple',
    price: 189.95,
    change: 2.1,
    percentChange: 1.12,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
  {
    id: '8',
    symbol: 'META',
    company: 'Meta',
    price: 512.30,
    change: 6.2,
    percentChange: 1.22,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
  {
    id: '9',
    symbol: 'AMZN',
    company: 'Amazon',
    price: 185.50,
    change: -3.5,
    percentChange: -1.86,
    sector: 'Retail',
    sectorColor: '#10b981',
  },
  {
    id: '10',
    symbol: 'GOOGL',
    company: 'Alphabet',
    price: 155.75,
    change: 3.8,
    percentChange: 2.50,
    sector: 'Technology',
    sectorColor: '#8b5cf6',
  },
];

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: 'AI Surge Drives Tech Rally',
    description: 'Major tech stocks gain on AI optimism...',
    summary: 'NVIDIA and MSFT lead market gains as AI adoption accelerates across industries.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    relatedStocks: ['1', '6'],
  },
  {
    id: '2',
    title: 'Energy Sector Pressured by Rate Expectations',
    description: 'Oil prices fall on interest rate concerns...',
    summary: 'ExxonMobil drops 2% as markets price in potential rate hikes.',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    relatedStocks: ['5'],
  },
  {
    id: '3',
    title: 'Healthcare Innovation Index Hits Record',
    description: 'Biotech and pharma stocks surge...',
    summary: 'Healthcare sector climbs on strong drug approval news and clinical trial results.',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    relatedStocks: ['4'],
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: '1',
    slug: 'nvidia-ai-boom',
    title: 'The AI Boom Driving NVIDIA Higher',
    subtitle: 'Understanding why AI is revolutionizing chip demand',
    summary: 'NVIDIA has become the center of the AI revolution. Let\'s explore what\'s driving their growth.',
    image: '',
    createdAt: new Date(),
    readTime: 8,
    slides: [
      {
        id: '1-1',
        slideType: 'hook',
        title: 'NVIDIA\'s Remarkable Rise',
        content: 'NVIDIA has become the most valuable chip maker in the world. Their stock has gained over 200% in the past year.',
      },
      {
        id: '1-2',
        slideType: 'what-happened',
        title: 'What Sparked This Move?',
        content: 'The explosion of AI adoption has created massive demand for chips that can process machine learning workloads efficiently.',
      },
      {
        id: '1-3',
        slideType: 'why-it-matters',
        title: 'Why This Matters',
        content: 'Every major tech company from OpenAI to Google is racing to build AI infrastructure. NVIDIA\'s chips are essential.',
      },
      {
        id: '1-4',
        slideType: 'key-movers',
        title: 'Key Players Affected',
        content: 'This trend is benefiting chip makers and AI software companies across the board.',
        stocks: [MOCK_STOCKS[0], MOCK_STOCKS[6]],
      },
      {
        id: '1-5',
        slideType: 'bigger-picture',
        title: 'Market Implications',
        content: 'Technology sector strength is supporting broader market gains and reshaping competitive dynamics.',
      },
      {
        id: '1-6',
        slideType: 'what-to-watch',
        title: 'What to Watch Next',
        content: 'Keep an eye on quarterly earnings reports and any regulation that might impact AI adoption.',
      },
      {
        id: '1-7',
        slideType: 'explore',
        title: 'Explore Related Stocks',
        content: 'Interested in learning more? Check out other tech companies benefiting from the AI trend.',
      },
    ],
  },
  {
    id: '2',
    slug: 'tesla-margin-watch',
    title: 'Tesla Faces a Margin Stress Test',
    subtitle: 'Price cuts, EV demand, and what investors are tracking now',
    summary: 'Tesla growth remains strong, but margins are the central debate as competition rises.',
    image: '',
    createdAt: new Date(),
    readTime: 7,
    slides: [
      {
        id: '2-1',
        slideType: 'hook',
        title: 'Why Margins Matter Right Now',
        content: 'Tesla can still grow deliveries while profit per vehicle changes. That trade-off is driving most analyst debates.',
      },
      {
        id: '2-2',
        slideType: 'what-happened',
        title: 'What Changed This Quarter',
        content: 'Vehicle pricing stayed competitive in multiple regions while production efficiency improved gradually.',
      },
      {
        id: '2-3',
        slideType: 'why-it-matters',
        title: 'Investor Focus',
        content: 'If software and energy revenues grow faster, they could offset pressure from auto gross margin.',
      },
      {
        id: '2-4',
        slideType: 'key-movers',
        title: 'Who Else Is Affected',
        content: 'Battery suppliers and charging infrastructure companies may move with sentiment around EV demand.',
        stocks: [MOCK_STOCKS[1], MOCK_STOCKS[8]],
      },
      {
        id: '2-5',
        slideType: 'what-to-watch',
        title: 'What To Watch Next',
        content: 'Track delivery growth, automotive gross margin ex-credits, and commentary on lower-cost models.',
      },
    ],
  },
  {
    id: '3',
    slug: 'bank-earnings-readthrough',
    title: 'What Big-Bank Earnings Say About the Economy',
    subtitle: 'Credit quality, deposits, and loan demand in focus',
    summary: 'Bank results can offer an early read on consumer and business confidence before macro data catches up.',
    image: '',
    createdAt: new Date(),
    readTime: 6,
    slides: [
      {
        id: '3-1',
        slideType: 'hook',
        title: 'Banks As A Macro Signal',
        content: 'Large banks process consumer spending, corporate borrowing, and credit trends in real time.',
      },
      {
        id: '3-2',
        slideType: 'what-happened',
        title: 'The Latest Earnings Themes',
        content: 'Net interest income stabilized while investment banking and trading activity improved from recent lows.',
      },
      {
        id: '3-3',
        slideType: 'bigger-picture',
        title: 'Why The Market Cares',
        content: 'If loan growth holds and charge-offs stay contained, investors often interpret that as resilience in the real economy.',
      },
      {
        id: '3-4',
        slideType: 'key-movers',
        title: 'Names To Track',
        content: 'Watch diversified banks and payment players for read-through effects on sentiment.',
        stocks: [MOCK_STOCKS[2], MOCK_STOCKS[6]],
      },
      {
        id: '3-5',
        slideType: 'explore',
        title: 'Where To Dig Deeper',
        content: 'Compare management commentary on consumer health with regional bank trends and credit card delinquencies.',
      },
    ],
  },
];
